from time import sleep
print("\t\t\t\t\U0001F476")
sleep(1)
print("\U0001F476")
print("\U0001F469")
# print("\t\t\t\t########################\n\t\t\t\t# Happy Children's Day #\n\t\t\t\t########################")
print("\t\t\t\t########################")
print("\t\t\t\t# Happy Children's Day #")
print("\t\t\t\t########################")
print("\U0001F476")
