from fabulous.color import bold, red, green, yellow, blue, white
from time import sleep
print("Command Executed...")
sleep(0.5)
print(bold(green("[+] "), red("Injecting Code ...")))
s1 = "1010111001001110"
s2 = "!:@#>$%^&*<~"
s3 = "zxcvbnmPOIUYTRghjsfld"

for i in range(20):
    if i % 2 == 0:
        print(s1, s2, s3, end=".")
    else:
        print(s2[::-1], s1[::-1], s3[::-1], end=".")

sleep(1)
print(bold(green("\n[+] "), yellow("Unpacking modules ...")))
sleep(0.5)
print("processing...")
print(bold(white("1%")))
sleep(1)
print(bold(white("10%")))
sleep(0.5)
print(bold(white("27%")))
sleep(0.5)
print(bold(white("78%")))
sleep(0.2)
print(bold(green("100%")))
sleep(2)
print(bold(green("\n[+] "), yellow("Setting Up System ...")))
sleep(1)
print("sys under control\n")
sleep(2)
print(bold(red("\t\t >>> Access Gained <<<")))
sleep(0.5)
print("\n")
print(bold(red("[+] "), white("Checking Sys status ...")))
sleep(1)
print(bold(red("\n Found: 2 issues")))
sleep(0.5)
print(bold(white("\n Working On It ...")))
sleep(1)
print(bold(green("[1]: "), white("Fixed")))
print("Results: ")
sleep(1)
print(bold(blue("Truth ...")))
sleep(0.5)
print(bold(blue("Non-Violence ...")))
sleep(0.5)
print(bold(blue("Peace ...")))
sleep(1)
print("\n")
print(bold(green("[2]: "), white("Fixed")))
print("Results: ")
sleep(1)
print(bold(blue("Jai Jawan ...")))
sleep(0.5)
print(bold(blue("Jai Kisan ...")))
sleep(2)
print(bold(yellow("\t\t Wishes: ")))
print(bold(red("\t\t Gandhi Jayanti")))
print(bold(red("\t\t Lal Bahadur Shastri Jayanti")))
