from fabulous.color import bold, green, red, yellow, blue
from time import sleep
print("\t\t", bold(yellow("I will set your screens on "), red("FIRE !!!")))
sleep(1)
print("\n"*10)
print(bold(green("\t\t\t*")))
sleep(1)
print("\n"*25)
print(bold(green("\t\t\t \\ | /")))
print(bold(yellow("\t\t\t - * -")))
print(bold(green("\t\t\t / | \\")))
print("\n"*5)
# first one
sleep(1)
print("\n"*25)
print(bold(yellow("\t\t .   |   .")))
print(bold(red("\t\t   \\   /")))
print(bold(yellow("\t\t -   "), green("*"), yellow("   -")))
print(bold(red("\t\t   /   \\")))
print(bold(yellow("\t\t .   |   .")))
print("\n"*5)
# second one
sleep(1)
print("\n"*25)
print(bold(yellow("\t\t\t .   |   .")))
print(bold(red("\t\t\t   \\   /")))
print(bold(yellow("\t\t\t -   "), green("*"), yellow("   -")))
print(bold(red("\t\t\t   /   \\")))
print(bold(yellow("\t\t\t .   |   .")))
print("\n"*8)
# third one
sleep(1)
print("\n"*25)
print(bold(yellow("\t\t\t\t .   |   .")))
print(bold(red("\t\t\t\t   \\   /")))
print(bold(yellow("\t\t\t\t -   "), green("*"), yellow("   -")))
print(bold(red("\t\t\t\t   /   \\")))
print(bold(yellow("\t\t\t\t .   |   .")))
print("\n"*10)
# fourth one
sleep(1)
print("\n"*25)
print(bold(red("\t\t\t\t        +")))
print(bold(yellow("\t\t\t\t    .   |   .")))
print(bold(red("\t\t\t\t      \\   /")))
print(bold(red("\t\t\t\t +  "), yellow("-   "),
      green("*"), yellow("   -"), red("  +")))
print(bold(red("\t\t\t\t      /   \\")))
print(bold(yellow("\t\t\t\t    .   |   .")))
print(bold(red("\t\t\t\t        +")))
print("\n"*5)
sleep(1)
print(bold(yellow("\t\t\t\t Happy "), red("Diwali "), yellow("Folks")))
print("\n"*3)
